apiVersion: apps/v1
kind: Deployment
metadata:
  name: buddy-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: buddy-container
        image: mq3274/buddy:v2

        ports:
        - containerPort: 80